// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Affix: typeof import('./src/components/affix.vue')['default']
    Aspect: typeof import('./src/components/aspect.vue')['default']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    Image: typeof import('./src/components/image.vue')['default']
  }
}

export { }
